spring:
  application:
    name: ressource-service
  datasource:
    url: jdbc:mysql://ressourcedb:3306/ressourceConstruction?createDatabaseIfNotExist=True
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

