#spring:
#  application:
#    name: gateway-service
#  main:
#    web-application-type: reactive
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#server:
#  port: 8888


spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          google:
#            client-id: 409734901312-314navrcqs74isaa9fg25873h46dkk7o.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/**
          filters:
            - RemoveRequestHeader=Authorization
        - id: tache-service
          uri: lb://TACHESERVICE
          predicates:
            - Path=/tache-service/**
          filters:
            - RemoveRequestHeader=Authorization
        - id: ressource-service
          uri: lb://RESSOURCE-SERVICE
          predicates:
            - Path=/ressource-service/**
          filters:
            - RemoveRequestHeader=Authorization

server:
  port: 8888



