spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://userdb:3306/userConstruction?createDatabaseIfNotExist=True
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

